apiVersion: v1
kind: Namespace
metadata:
  name: tfb-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfb-frontend-deploy
  namespace: tfb-frontend
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: tfb-frontend
  template:
    metadata:
      labels:
        app: tfb-frontend
    spec:
      containers:
      - name: tfb-frontend
        image: nginx
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tfb-frontend-svc
  namespace: tfb-frontend
  labels:
    app: tfb-frontend
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: tfb-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: tfb-frontend-ingress
 namespace: tfb-frontend
 annotations:
   cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
  - hosts:
    - codingpirates.rosenvold.tech
    secretName: codingpirates-tls
  rules:
  - host: codingpirates.rosenvold.tech
    http:
      paths:
      - backend:
          service:
            name: tfb-frontend-svc
            port:
              number: 80
        path: /
        pathType: Prefix