apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IudGhlZmx5aW5nYmlyZHMubmV0Ijp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6Ii1KSEllUi1YbEQwNTlkdXciLCJhdXRoIjoiWVdSdGFXNDZMVXBJU1dWU0xWaHNSREExT1dSMWR3PT0ifX19
kind: Secret
metadata:
  name: regcred
  namespace: website
type: kubernetes.io/dockerconfigjson
